apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-0
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/0"
  claimRef:
    name: my-elastic-cluster-master-my-elastic-cluster-master-0
    namespace: es
